version: '3.8'
services:
  broker:
    image: apache/kafka:4.0.0
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
      - '19092:19092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo
    container_name: ersms-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: stock

    volumes:
      - "./data/mongo:/data/db"

  main-service:
    image: dtomala/ersms-main-service
    container_name: main-service
    ports:
      - '8091:8091'
    env_file: "main.env"
    depends_on:
      broker:
        condition: service_healthy

  stock-service:
    image: dtomala/ersms-stock-service
    container_name: stock-service
    ports:
      - '8000:8000'
    env_file: "stock.env"
    depends_on:
      broker:
        condition: service_healthy

  payment-service:
    image: dtomala/ersms-payment-service
    container_name: payment-service
    ports:
      - '8092:8092'
    env_file: "payment.env"
    depends_on:
      broker:
        condition: service_healthy

  frontend-service:
    image: pploski060/ersms-front-end
    container_name: frontend-service
    ports:
      - '5000:5000'
    env_file: "frontend.env"
    depends_on:
      broker:
        condition: service_healthy